# Generated by Django 5.0.7 on 2024-07-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_banner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='background/'),
        ),
    ]
