# Generated by Django 5.0.7 on 2024-07-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_banner_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='productsmenu',
            name='category',
        ),
        migrations.AddField(
            model_name='productsmenu',
            name='category',
            field=models.ManyToManyField(to='main.category'),
        ),
    ]
